[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "16.13.2", RUBY_VERSION = "2.7.1" }

[context.deploy-preview]
  environment = { NODE_VERSION = "16.13.2", RUBY_VERSION = "2.7.1" }

[dev]
  command = "npm run dev"
  publish = "build"
  port = 3000
  targetPort = 8080
  framework = "#custom"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://rsms.me https://api.netlify.com https://www.googleadservices.com https://www.google-analytics.com *.googleapis.com *.gstatic.com; style-src 'self' https://rsms.me *.googleapis.com 'unsafe-inline'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://www.googleadservices.com https://www.google-analytics.com www.google-analytics.com ajax.googleapis.com apis.google.com www.googletagmanager.com *.googleapis.com; img-src 'self' data: https://www.googleadservices.com www.w3.org https://ssl.gstatic.com https://www.gstatic.com https://www.googletagmanager.com; worker-src 'self' blob:;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Access-Control-Allow-Origin = "*"
